# Generated by Django 3.1.3 on 2020-11-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
