# Generated by Django 3.1.3 on 2020-11-18 16:45

from __future__ import unicode_literals
from django.db import migrations


def create_initial_team_members(apps, schema_editor):
    TeamMember = apps.get_model('team_member', 'TeamMember')

    TeamMember.objects.create(
        first_name='Poorva', last_name='Parkhi', phone_number=9990361047, role='Admin',
        email='poorvaparkhi@gmail.com')
    TeamMember.objects.create(
        first_name='John', last_name='Oliver', phone_number=9938328047, role='Regular',
        email='johnoli@gmail.com')
    TeamMember.objects.create(
        first_name='Adam', last_name='Driver', phone_number=9938328047, role='Regular',
        email='adamdriver@gmail.com')
    TeamMember.objects.create(
        first_name='Christian', last_name='Bale', phone_number=9938328047, role='Regular',
        email='christian_bale@gmail.com')
    TeamMember.objects.create(
        first_name='Rachel', last_name='Green', phone_number=9938328047, role='Admin',
        email='rachel_green@gmail.com')
    TeamMember.objects.create(
        first_name='Chandler', last_name='Bing', phone_number=9938328047, role='Regular',
        email='chandler_bing@gmail.com')
    TeamMember.objects.create(
        first_name='Andrea', last_name='Grandi', phone_number=9938328047, role='Admin',
        email='andrea_grandi@gmail.com')

class Migration(migrations.Migration):

    dependencies = [
        ('team_member', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_team_members),
    ]
