# Generated by Django 3.1.3 on 2020-11-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_member', '0002_auto_20201116_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
